<?php

$modversion['name'] = _MI_ACC_NAME;
$modversion['version'] = '0.90';
$modversion['description'] = _MI_ACC_DESC;
$modversion['credits'] = _MI_ACC_CREDITS;
$modversion['author'] = _MI_ACC_AUTHOR;
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'logo.gif';
$modversion['dirname'] = 'ac_counter';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
$modversion['sqlfile']['pgsql'] = 'sql/pgsql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'ac_counter';
$modversion['tables'][1] = 'just_counter';

// Menu
$modversion['hasMain'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Templates
$modversion['templates'][1]['file'] = 'counter_index.html';
$modversion['templates'][1]['description'] = 'カウンター';

// Blocks
$modversion['blocks'][1]['file'] = 'block.php';
$modversion['blocks'][1]['name'] = 'アクセスカウンター';
$modversion['blocks'][1]['description'] = 'アクセス管理カウンター';
$modversion['blocks'][1]['show_func'] = 'b_ac_counter';
$modversion['blocks'][1]['template'] = 'counter_block.html';

$modversion['blocks'][2]['file'] = 'block.php';
$modversion['blocks'][2]['name'] = 'ページカウンター';
$modversion['blocks'][2]['description'] = 'アクセス管理カウンター';
$modversion['blocks'][2]['show_func'] = 'b_ac_mini_counter';
$modversion['blocks'][2]['template'] = 'counter_mini_block.html';
